from sqlalchemy import MetaData, Column, Table, Integer, String, ForeignKey
from database import base

metadata = MetaData()

class Sociology(base):
    __tablename__ = "sociology"

    id = Column(Integer, primary_key=True, autoincrement=True)
    zakalivanie_opinion = Column('Закаливание_мнение', String, nullable=False)
    start_age = Column('Возраст_начала', String, nullable=False)
    health_effect = Column('Эффект_самочувствие', Integer, nullable=False)
    zabolevanie_effect = Column('Эффект_заболеваемость', Integer, nullable=False)
    rabotosposobnost_effect = Column('Эффект_работоспособность', Integer, nullable=False)
    organism_effect = Column('Эффект_организм', Integer, nullable=False)
    ustoychivost_effect = Column('Эффект_устойчивость', Integer, nullable=False)
    organi_effect = Column('Эффект_органы', Integer, nullable=False)
    remission_effect = Column('Эффект_ремиссия', Integer, nullable=False)
    energy_effect = Column('Эффект_энергия', Integer, nullable=False)
    life_quality_effect = Column('Эффект_качество_жизни', Integer, nullable=False)
    stress_pcyhoeffect = Column('Психоэффект_стресс', Integer, nullable=False)
    samocontrol_pcyhoeffect = Column('Психоэффект_самоконтроль', Integer, nullable=False)
    vibe_pcyhoeffect = Column('Психоэффект_настроение', Integer, nullable=False)
    privichka_pcyhoeffect = Column('Психоэффект_привычка', Integer, nullable=False)
    memory_pcyhoeffect = Column('Психоэффект_память', Integer, nullable=False)
    trevoga_pcyhoeffect = Column('Психоэффект_треога', Integer, nullable=False)
    adaptation_confidence = Column('Уверенность_адаптация', String, nullable=False)
    period_practis = Column('Период_практики', String, nullable=False)
    chastota_practiki = Column('Частота_практики', String, nullable=False)
    pererivs_practiks = Column('Перерывы_практики', String, nullable=False)
    sposobi_practiks = Column('Способы_практики', String, nullable=False)
    sochetania_banya = Column('Сочетание_баня', String, nullable=False)
    sex = Column('Пол', String, nullable=False)
    age = Column('Возвраст', Integer, nullable=False)
    region = Column('Регион', String, nullable=False)
    semeinoe_polojenye = Column('Семейное_положение', String, nullable=False)
    deyatelnost = Column('Деятельность', String, nullable=False)
    obrathovanye = Column('Образование', String, nullable=False)
    proffesion = Column('Профессия', String, nullable=False)
    motivi_zakalivalia = Column('Мотивы_закаливания', String, nullable=False)
    negativ_factors = Column('Негативные_факторы', String, nullable=False)
    practis_tips_zakalivanya = Column('Практикуемые_типы_закаливания', String, nullable=False)
    istochniki_information_po_teme_zakalivanya = Column('Источники_информации_по_теме_закаливания', String, nullable=False)
    metods_popylyarizaci_zakalivanya = Column('Методы_популяризации_закаливания', String, nullable=False)
